version: 2.1
orbs:
    codecov: codecov/codecov@1.1.3
    gh: circleci/github-cli@1.0.3
    browser-tools: circleci/browser-tools@1.2.4
jobs:
    build_library:
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                  keys:
                      - v2-dependencies-react-{{ checksum "components/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd components
                      yarn install --frozen-lockfile
            - save_cache:
                  name: Save Cache
                  paths:
                      - components/node_modules
                  key: v2-dependencies-react-{{ checksum "components/yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      cd components
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      cd components
                      yarn lint
            - run:
                  name: Test
                  command: |
                      yarn test --coverage --watchAll=false --maxWorkers=2
            - run:
                  name: Build Library
                  command: |
                      yarn build
            - run:
                  name: Test Artifacts
                  command: |
                      yarn test:artifacts
            - run:
                  name: NPM Package
                  command: |
                      cd dist && npm pack
            # Save the dist folder for use in future jobs.
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist
                      - components/coverage
            - run:
                  command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
                  when: always
    coverage_report:
        working_directory: ~/react-component-library
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - codecov/upload:
                  file: './components/coverage/clover.xml'
                  token: 5e6faafe-eaf0-4d71-a931-22f279d3e446

    # Builds the Showcase app using @brightlayer-ui/react-components persisted in /dist folder.
    build_showcase:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: Initialize Submodule
                  command: |
                      git submodule init && git submodule update
            - restore_cache:
                  keys:
                      - v2-dependencies-react-{{ checksum "demos/showcase/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd demos/showcase
                      yarn install --frozen-lockfile

                      # Install the packed version of @brightlayer-ui/react-components
                      PACKAGED_VERSION=`node -p "require('../../dist/package.json').version"`
                      yarn add ../../dist/brightlayer-ui-react-components-$PACKAGED_VERSION.tgz
            - save_cache:
                  name: Save Cache
                  paths:
                      - demos/showcase/node_modules
                  key: v2-dependencies-react-{{ checksum "demos/showcase/yarn.lock" }}
            # This will be prettier checked on the demo repository
            # - run:
            #       name: Prettier Check
            #       command: |
            #           cd demos/showcase
            #           yarn prettier:check
            - run:
                  name: Build Showcase
                  command: |
                      cd demos/showcase
                      yarn build
            - run:
                  command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
                  when: always

    # Builds the React Dev app using @brightlayer-ui/react-components persisted in /dist folder.
    build_reactdev:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
            - DEV_BRANCH: dev
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - restore_cache:
                  keys:
                      - v2-dependencies-react-{{ checksum "docs/yarn.lock" }}
            - run:
                  name: Install Dependencies
                  command: |
                      cd docs
                      yarn install --frozen-lockfile

                      # Install the packed version of @brightlayer-ui/react-components
                      PACKAGED_VERSION=`node -p "require('../dist/package.json').version"`
                      yarn add ../dist/brightlayer-ui-react-components-$PACKAGED_VERSION.tgz
            - save_cache:
                  name: Save Cache
                  paths:
                      - docs/node_modules
                  key: v2-dependencies-react-{{ checksum "docs/yarn.lock" }}
            - run:
                  name: Prettier Check
                  command: |
                      cd docs
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      cd docs
                      yarn lint
            - run:
                  name: Build React Dev
                  command: |
                      cd docs
                    
                      if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
                        export PUBLIC_URL=/react
                      else
                        export PUBLIC_URL=/react-dev
                      fi
                    
                      yarn build
                      cp public/404.html build
            - run:
                  command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
                  when: always
            - persist_to_workspace:
                  root: .
                  paths:
                      - docs/build

    deploy_reactdev:
        docker:
            - image: cimg/node:14.19.0-browsers
        environment:
            - MASTER_BRANCH: master
            - DEV_BRANCH: dev
            - DEV_TARGET: https://github.com/brightlayer-ui-components/react-dev
            - MASTER_TARGET: https://github.com/brightlayer-ui-components/react
            - GH_EMAIL: brightlayer-ui@eaton.com
            - GH_NAME: Brightlayer UI Agent
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: Deploy Dev Doc
                  command: |
                      git config --global user.email "$GH_EMAIL"
                      git config --global user.name "$GH_NAME"

                      cd docs

                      if [ $CIRCLE_BRANCH == $MASTER_BRANCH ]; then
                        git clone $MASTER_TARGET out
                      else
                        git clone $DEV_TARGET out
                      fi

                      cd out
                      git rm -rf .
                      cd ..

                      cp -a build/. out/.
                      cd out

                      git add -A
                      git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
                      git push
    publish:
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run:
                  name: Authenticate with registry
                  command: |
                      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
                      echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                  name: Publish @brightlayer-ui/react-components
                  command: |
                      yarn publish:package -b $CIRCLE_BRANCH

    tag:
        docker:
            - image: cimg/node:14.19.0-browsers
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - gh/setup
            - run:
                  name: Tag @brightlayer-ui/react-components
                  command: |
                      yarn tag:package -b $CIRCLE_BRANCH -s -blui-react-components

workflows:
    version: 2
    react_library:
        jobs:
            - build_library
            # - build_showcase:
            #   requires:
            #       - build_library
            # - build_storybook:
            #       requires:
            #           - build_library
            - deploy_reactdev:
                  requires:
                      - build_reactdev
            #       filters:
            #           branches:
            #               only:
            #                   - master
            #                   - dev
            - build_reactdev:
                  requires:
                      - build_library
            - publish:
                  requires:
                      - build_library
                      - build_reactdev
                  filters:
                      branches:
                          only:
                              - master
                              - dev
            - tag:
                  requires:
                      - publish
                  filters:
                      branches:
                          only:
                              - master
            - coverage_report:
                  requires:
                      - build_library
                  filters:
                      branches:
                          only:
                              - master
